# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-31 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_privacy_settings', '0002_privacypolicysetting_popup_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicysetting',
            name='cookie_notice',
            field=models.TextField(blank=True, default='Notice...', null=True, verbose_name='Notice popup bottom'),
        ),
        migrations.AlterField(
            model_name='privacypolicysetting',
            name='popup_intro',
            field=models.TextField(blank=True, default='Introduction...', null=True, verbose_name='Popup introduction'),
        ),
    ]
