# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-01 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_privacy_settings', '0005_auto_20180601_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicycategory',
            name='slug',
            field=models.SlugField(default='essentials', verbose_name='Id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privacypolicycategory',
            name='title',
            field=models.CharField(default='statistics', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
