# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-01 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_privacy_settings', '0006_auto_20180601_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicycategory',
            name='title',
        ),
    ]
